### PR TITLE
add new flag --sync-ping

### PR DESCRIPTION
**Pull request by ramok**

### CODE REVIEW

**Comment by famzah** [comment]
Hi @ramok. I have two things to discuss:

- What is the practical purpose of this new switch? When do we need to send the same amount of pings?

- Let's call the newly added code in print_ping_data() the "trigger new ping for all hosts" code. I think that we shouldn't place the "trigger new ping for all hosts" code in print_ping_data(), because it has nothing to do with printing data. Additionally, right now it delays the printing until all hosts returned a ping (or timed out) which defers the real-time printing of results. Why do we want to wait until all hosts return data, and then finally print all ping results at once?
  - I think we should leave print_ping_data() with no changes, so that we see the ping results immediately (asynchronously).
  - The "trigger new ping for all hosts" code should go in a separate function named trigger_sync_ping(), for example, which should be part of main while(1) loop along with handle_pressed_keys(), print_ping_data(), etc.

**Comment by famzah** [comment]
One other thing. The new short `-s` option is the same as the old `-s` (which we removed). In order to avoid confusion, shouldn't we use another short option? Maybe `-S` (upper-case)?

**Comment by ramok** [comment]
> What is the practical purpose of this new switch? When do we need to send the same amount of pings?

There is [example](http://core.org.ua/tmp/komar-window-2017-10-24-203948.png). In ping-multi on top I cannot say if host 192.168.0.2 and 192.168.0.3 going down in same time or not. If they going down in same time, most likely problem not in this hosts, but in switch or cable which they are connected together.
I found this very useful :)

All your remark are absolutely right, I will make fix according them.

**Comment by famzah** [comment]
Thank you for your contribution!

**Pull request merged**
